/* ProTrack OS v2.1 production-readiness layer — resolves the blocking audit without changing scoring. */
var PTP = {version:"2.1.0",setupRequired:false,setup:{academy:{},head:{},assistant:{},player:{},logo:""},users:[]};
var PTP_PREV_RENDER=osRender, PTP_PREV_PROFILE=osProfileTabContent, PTP_PREV_ALERTS=osAlerts, PTP_PREV_ACTIONS=osActions;

Object.assign(OS.dict.en,{dashboard_title:"Tonight's coaching brief",dashboard_sub:"The decisions and player signals to resolve before tomorrow's first session.",actions:"Tonight's priorities",actions_sub:"Recommended actions ordered by urgency",alerts:"Performance signals",alerts_sub:"Attendance, progression and package risks that need attention",account_sub:"Your protected academy account"});
Object.assign(OS.dict.fa,{dashboard_title:"گزارش مدیریتی امشب",dashboard_sub:"تصمیم‌ها و وضعیت بازیکنانی که باید پیش از نخستین جلسه فردا بررسی شوند.",actions:"اولویت‌های امشب",actions_sub:"اقدام‌های پیشنهادی به‌ترتیب اهمیت",alerts:"نشانه‌های مهم عملکرد",alerts_sub:"هشدارهای حضور، پیشرفت و اعتبار جلسات که نیاز به پیگیری دارند",account_role:"حساب و امنیت",account_sub:"حساب امن آکادمی",morning:"مرکز عملکرد",nightly:"مرکز فرمان مربی",players_sub:"پرونده کامل، سوابق ورزشی و مسیر رشد بازیکنان",settings_sub:"حساب، امنیت، نصب و اطلاعات آکادمی"});

function ptpMigrate(){
  const d=OS.data,a=d.academy;
  if(!d.players.some(p=>p.id==="p1")&&!d.archivedPlayers?.some(p=>p.id==="p1")&&(state.analyses.some(x=>x.playerName==="Luca Marino")||(a.name==="ProTrack Private Coaching"&&d.players.some(p=>p.id==="p3"))))d.players.unshift({id:"p1",name:"Luca Marino",gender:"Male",age:24,phone:"+39 333 842 190",emergency:"Marco · +39 333 842 188",startDate:"2025-01-08",stage:"Development",track:"Development",status:"Active",pdi:6.3,pti:6.7,rubricMin:6,confidence:"HIGH",sessionsCompleted:12,attendance:{attended:31,missed:2,consecutive:0},coachId:"c1",coach:"Yekta · Head Coach",coachNotes:"Strong response to positioning work. Volley stability remains the main limiter.",membership:"Performance 40",sessionsPurchased:40,sessionsUsed:33,primaryFocus:"Volley",pdiHistory:[5.8,6,6.3],ptiHistory:[5.9,6.2,6.7],commitment:8,commitmentTrend:"stable",nationality:"International",dominantHand:"Right",playingSide:"Left",goals:"Competition readiness",rankings:{club:2,city:18,national:92,international:null}});
  Object.assign(a,{aboutEn:a.aboutEn||"ProTrack is a performance academy built around sustainable development, better decisions and measurable progress.",aboutFa:a.aboutFa||"ProTrack آکادمی تخصصی رشد پایدار بازیکن، تصمیم‌گیری بهتر و پیشرفت قابل‌اندازه‌گیری است.",instagram:a.instagram||"@protrack.coaching",whatsapp:a.whatsapp||a.phone,address:a.address||a.location,programs:a.programs||["Private Coaching","Performance Analysis","Competition Preparation"],tracks:a.tracks||["Starter","Foundation","Development","Competition","Elite"]});
  d.coaches.forEach((c,i)=>{c.bioEn||=i?"Coach focused on technical development and tactical decision-making.":"Head coach and academy performance pathway director.";c.bioFa||=i?"مربی توسعه تکنیک و تصمیم‌گیری تاکتیکی.":"سرمربی و مدیر مسیر عملکرد آکادمی.";c.email||=`${c.name.split(" ")[0].toLowerCase()}@protrack.local`;if(!Array.isArray(c.certifications)||typeof c.certifications[0]==="string")c.certifications=(c.certifications||[]).map((x,j)=>({name:x,issuer:"ProTrack Academy",expiry:`202${8+j}-12-31`,verified:true}));if(!c.certifications.length)c.certifications=[{name:"ProTrack Coaching Passport",issuer:"ProTrack Academy",expiry:"2028-12-31",verified:true}];});
  d.players.forEach((p,i)=>{p.sportsBackgroundEn||=i%2?"Recreational racket-sport background; developing match structure.":"Competitive recreational athlete with structured padel training.";p.sportsBackgroundFa||=i%2?"سابقه تفریحی در ورزش‌های راکتی؛ در حال تقویت ساختار مسابقه.":"ورزشکار تفریحی رقابتی با تمرین ساختاریافته پدل.";p.sportsBackground||=OS.lang==="fa"?p.sportsBackgroundFa:p.sportsBackgroundEn;p.goals||=p.primaryFocus;p.rankings||={club:i+2,city:i<3?18+i*4:null,national:i===0?92:null,international:null};});
  d.tournaments.forEach(t=>{t.level||="Club";t.result||="Registered";t.partner||="TBD";t.position||="—";});
  pt2Save();
}
ptpMigrate();

function ptpField(label,name,value="",type="text",required=true){return `<div class="os-field"><label>${label}</label><input name="${name}" type="${type}" value="${osEsc(value)}" ${required?"required":""}></div>`;}
function ptpStepper(step){return `<div class="ptp-setup-progress"><span>${step}/6</span><div>${Array.from({length:6},(_,i)=>`<i class="${i<step?"done":""}"></i>`).join("")}</div></div>`;}
function ptpSetupCopy(step){const en=["Create academy","Create head coach","Academy information","Brand identity","First assistant coach","First player"],fa=["ساخت آکادمی","ساخت حساب سرمربی","اطلاعات آکادمی","هویت بصری","نخستین مربی دستیار","نخستین بازیکن"];return OS.lang==="fa"?fa[step-1]:en[step-1];}

function ptpOpenSetup(step=1){
  const s=PTP.setup,fa=OS.lang==="fa";let fields="",optional="";
  if(step===1)fields=`${ptpField(fa?"نام آکادمی":"Academy name","name",s.academy.name||"ProTrack Private Coaching")}${ptpField(fa?"شهر / کشور":"City / country","location",s.academy.location||"")}`;
  if(step===2)fields=`${ptpField(fa?"نام کامل سرمربی":"Head coach full name","name",s.head.name||"")}${ptpField(fa?"نام کاربری":"Username","username",s.head.username||"")}${ptpField(fa?"رمز عبور (حداقل ۱۰ کاراکتر)":"Password (10+ characters)","password",s.head.password||"","password")}`;
  if(step===3)fields=`<div class="os-field"><label>${fa?"درباره آکادمی":"About the academy"}</label><textarea name="about" required>${osEsc(s.academy.about||"")}</textarea></div><div class="pt2-field-pair">${ptpField(fa?"تلفن":"Phone","phone",s.academy.phone||"")}${ptpField("WhatsApp","whatsapp",s.academy.whatsapp||"")}</div>${ptpField("Instagram","instagram",s.academy.instagram||"@")}${ptpField(fa?"نشانی کامل":"Full address","address",s.academy.address||"")}`;
  if(step===4)fields=`<div class="ptp-logo-upload"><div class="ptp-logo-preview"><img src="${s.logo||"assets/protrack-official.png"}" alt="ProTrack"></div><label class="os-secondary-button" for="ptpLogoFile">${fa?"انتخاب لوگوی رسمی":"Choose official logo"}</label><input id="ptpLogoFile" type="file" accept="image/png,image/jpeg,image/webp" hidden><small>${fa?"PNG یا JPG، حداکثر ۲ مگابایت. در صورت عدم انتخاب، لوگوی رسمی ProTrack استفاده می‌شود.":"PNG or JPG, up to 2 MB. The official ProTrack logo remains the default."}</small></div>`;
  if(step===5){optional=fa?"اختیاری":"Optional";fields=`${ptpField(fa?"نام کامل مربی":"Assistant full name","name",s.assistant.name||"","text",false)}${ptpField(fa?"نام کاربری":"Username","username",s.assistant.username||"assistant","text",false)}${ptpField(fa?"رمز عبور (حداقل ۱۰ کاراکتر)":"Password (10+ characters)","password",s.assistant.password||"","password",false)}`;}
  if(step===6)fields=`${ptpField(fa?"نام کامل بازیکن":"Player full name","name",s.player.name||"")}${ptpField(fa?"شماره تماس":"Phone","phone",s.player.phone||"")}${ptpField(fa?"نام کاربری بازیکن":"Player username","username",s.player.username||"")}${ptpField(fa?"رمز عبور (حداقل ۱۰ کاراکتر)":"Password (10+ characters)","password",s.player.password||"","password")}`;
  const body=`<div class="ptp-setup-brand"><img src="assets/icon-192.png" alt="ProTrack"><span>PROTRACK OS</span></div>${ptpStepper(step)}<div class="ptp-setup-title"><span>${optional}</span><h1>${ptpSetupCopy(step)}</h1><p>${fa?"راه‌اندازی امن آکادمی را در چند گام کوتاه کامل کنید.":"Complete your secure academy setup in a few focused steps."}</p></div><form class="os-form" id="ptpSetupForm">${fields}<p class="pt2-form-error" id="ptpSetupError"></p><div class="ptp-wizard-actions">${step>1?`<button type="button" class="os-secondary-button" data-os-action="ptp-setup-back" data-step="${step}">${fa?"بازگشت":"Back"}</button>`:""}<button class="os-primary-button" type="submit">${step===6?(fa?"ساخت آکادمی":"Create academy"):(fa?"ادامه":"Continue")}</button></div></form>`;
  osOpenModal(osModalFrame("","",body,"ptp-setup-card"),"open ptp-setup-modal");
  const file=document.getElementById("ptpLogoFile");file?.addEventListener("change",()=>{const f=file.files[0];if(!f)return;if(f.size>2_000_000){document.getElementById("ptpSetupError").textContent=fa?"حجم فایل باید کمتر از ۲ مگابایت باشد.":"Logo must be smaller than 2 MB.";return;}const reader=new FileReader();reader.onload=()=>{s.logo=reader.result;document.querySelector(".ptp-logo-preview img").src=s.logo;};reader.readAsDataURL(f);});
  document.getElementById("ptpSetupForm").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());if(step===1)Object.assign(s.academy,data);if(step===2)Object.assign(s.head,data);if(step===3)Object.assign(s.academy,data);if(step===5)Object.assign(s.assistant,data);if(step===6)Object.assign(s.player,data);if(step<6){ptpOpenSetup(step+1);return;}const btn=e.target.querySelector("button[type=submit]");btn.disabled=true;try{const res=await fetch("/api/setup/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({academy:{...s.academy,address:s.academy.address||s.academy.location},head:s.head,assistant:s.assistant,player:s.player})});const out=await res.json();if(!res.ok)throw new Error(out.message);ptpApplySetup();PTP.setupRequired=false;osCloseModal();toast(fa?"آکادمی با موفقیت ساخته شد. اکنون وارد شوید.":"Academy created. You can now sign in.");osOpenLogin();}catch(err){document.getElementById("ptpSetupError").textContent=err.message||"Setup failed";btn.disabled=false;}});
}

function ptpApplySetup(){
  const s=PTP.setup,a=OS.data.academy;Object.assign(a,{name:s.academy.name,location:s.academy.location,address:s.academy.address,aboutEn:OS.lang==="fa"?a.aboutEn:s.academy.about,aboutFa:OS.lang==="fa"?s.academy.about:a.aboutFa,phone:s.academy.phone,whatsapp:s.academy.whatsapp,instagram:s.academy.instagram,logoDataUrl:s.logo||""});
  OS.data.coaches=[{id:"c1",name:s.head.name,title:"Head Coach",phone:s.academy.phone||"",email:"",specialty:"Academy direction & performance",bio:"",certifications:[],active:true}];
  if(s.assistant.name)OS.data.coaches.push({id:"c2",name:s.assistant.name,title:"Assistant Coach",phone:"",email:"",specialty:"Player development",bio:"",certifications:[],active:true});
  const p={id:"p1",name:s.player.name,gender:"—",age:"",phone:s.player.phone,emergency:"—",startDate:osDateOffset(0),stage:"Starter",track:"Starter",status:"Active",pdi:null,pti:null,rubricMin:null,confidence:"LOW",sessionsCompleted:0,attendance:{attended:0,missed:0,consecutive:0},coachId:"c1",coach:s.head.name,coachNotes:"",membership:"Starter",sessionsPurchased:0,sessionsUsed:0,primaryFocus:"Assessment required",pdiHistory:[],ptiHistory:[],commitment:null,commitmentTrend:"stable",nationality:"—",dominantHand:"Right",playingSide:"Right",sportsBackground:"",goals:"",rankings:{club:null,city:null,national:null,international:null}};
  OS.data.players=[p];OS.data.sessions=[];OS.data.quickNotes=[];OS.data.bookings=[];OS.data.registrations=[];OS.data.tournaments=[];OS.data.rankings=[];OS.data.achievements=[];OS.data.journey=[{id:pt2Id("j"),playerId:"p1",date:osDateOffset(0),title:"Joined ProTrack",detail:"First academy player",type:"milestone"}];state.analyses=[];saveAnalyses();pt2Save();
}

var PTP_LOGIN=osOpenLogin;
osOpenLogin=function(){
  if(document.querySelector("#osLoginForm,#ptpSetupForm"))return;const fa=OS.lang==="fa";
  const body=`<div class="os-login-logo"><img src="assets/icon-192.png" alt="ProTrack"></div><div class="os-login-title"><span class="eyebrow">PROTRACK OS v2.1</span><h1>${fa?"ورود به آکادمی":"Welcome back"}</h1><p>${fa?"با حساب امن آکادمی وارد شوید.":"Sign in with your secure academy account."}</p></div><form class="os-form" id="osLoginForm">${ptpField(fa?"نام کاربری":"Username","username",PTP.setup.head.username||"")}${ptpField(fa?"رمز عبور":"Password","password","","password")}<p class="pt2-form-error" id="pt2LoginError" role="alert"></p><button class="os-primary-button" type="submit">${fa?"ورود":"Sign in"}</button><button class="ptp-registration-link" type="button" data-os-action="ptp-start-setup">${PTP.setupRequired?(fa?"ساخت آکادمی جدید":"Create your academy"):(fa?"راهنمای ثبت‌نام و ساخت حساب":"Registration & account setup")}</button><p class="os-version">${fa?"دسترسی امن و سطح‌بندی‌شده":"Protected role-based access"}</p></form>`;
  osOpenModal(osModalFrame("","",body,"os-login-card"),"open");
  document.getElementById("osLoginForm").addEventListener("submit",async e=>{e.preventDefault();const btn=e.target.querySelector("button[type=submit]");btn.disabled=true;const fd=new FormData(e.target);try{const res=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:fd.get("username"),password:fd.get("password")})});const out=await res.json();if(!res.ok)throw new Error();OS.user={...out.user,loggedIn:true};osSave();PT2.authReady=true;osCloseModal();osRender("home");}catch(_){document.getElementById("pt2LoginError").textContent=fa?"نام کاربری یا رمز عبور درست نیست.":"The username or password is incorrect.";btn.disabled=false;}});
};

function ptpRanking(value){return value===null||value===undefined||value===""?"—":`#${value}`;}
osProfileTabContent=function(p,promo,rate,remaining,analyses){
  if(OS.profileTab==="passport")return `<section class="os-card os-detail-card ptp-passport"><div class="os-section-head"><div><span class="eyebrow">PROTRACK PLAYER PASSPORT</span><h2>${pt2Fa("Sporting identity","هویت ورزشی")}</h2><p>${pt2Fa("A complete, portable development record","پرونده یکپارچه و قابل‌استناد رشد بازیکن")}</p></div></div><div class="os-detail-grid">${[[pt2Fa("Full name","نام کامل"),p.name],[pt2Fa("Nationality","ملیت"),p.nationality],[pt2Fa("Dominant hand","دست غالب"),p.dominantHand],[pt2Fa("Playing side","سمت بازی"),p.playingSide],[pt2Fa("Assigned coach","مربی مسئول"),pt2Coach(p.coachId)?.name||p.coach],[pt2Fa("Current track","مسیر فعلی"),p.track]].map(([k,v])=>`<div class="os-detail"><small>${k}</small><strong>${osEsc(v||"—")}</strong></div>`).join("")}</div><div class="ptp-narrative"><div><small>${pt2Fa("Sports background","پیشینه ورزشی")}</small><p>${osEsc((OS.lang==="fa"?p.sportsBackgroundFa:p.sportsBackgroundEn)||p.sportsBackground||"—")}</p></div><div><small>${pt2Fa("Development goals","هدف‌های رشد")}</small><p>${osEsc(p.goals||"—")}</p></div></div></section>`;
  if(OS.profileTab==="competition"){const events=OS.data.tournaments.filter(x=>x.playerIds.includes(p.id));return `<section class="os-card os-detail-card"><div class="os-section-head"><div><h2>${pt2Fa("Tournament history","سابقه مسابقات")}</h2><p>${pt2Fa("Results, partner and final position","نتیجه، هم‌بازی و جایگاه نهایی")}</p></div>${pt2CanManage()?`<button class="pt2-head-action" data-os-action="ptp-add-tournament" data-player="${p.id}">＋ ${pt2Fa("Add result","ثبت نتیجه")}</button>`:""}</div><div class="ptp-responsive-table"><div class="ptp-table-header"><span>${pt2Fa("Tournament","مسابقه")}</span><span>${pt2Fa("Date / level","تاریخ / سطح")}</span><span>${pt2Fa("Result","نتیجه")}</span><span>${pt2Fa("Partner","هم‌بازی")}</span><span>${pt2Fa("Position","جایگاه")}</span></div>${events.map(x=>`<div class="ptp-table-row"><span><strong>${osEsc(x.name)}</strong><small>${osEsc(x.location)}</small></span><span>${pt2Date(x.date)}<small>${osEsc(x.level)}</small></span><span>${osEsc(x.result)}</span><span>${osEsc(x.partner)}</span><span><b>${osEsc(x.position)}</b></span></div>`).join("")||`<p class="pt2-empty">${pt2Fa("No tournament result has been recorded.","هنوز نتیجه مسابقه‌ای ثبت نشده است.")}</p>`}</div></section><section class="os-card os-detail-card ptp-ranking-card"><div class="os-section-head"><div><h2>${pt2Fa("Official ranking snapshot","نمای رتبه‌بندی")}</h2><p>${pt2Fa("Club to international standing","از باشگاه تا رده بین‌المللی")}</p></div></div><div class="ptp-ranking-grid">${[[pt2Fa("Club","باشگاه"),p.rankings.club],[pt2Fa("City","شهر"),p.rankings.city],[pt2Fa("National","کشوری"),p.rankings.national],[pt2Fa("International","بین‌المللی"),p.rankings.international]].map(([k,v])=>`<div><small>${k}</small><strong>${ptpRanking(v)}</strong></div>`).join("")}</div></section>`;}
  return PTP_PREV_PROFILE(p,promo,rate,remaining,analyses);
};

osAlerts=function(){const base=PTP_PREV_ALERTS(),seen=new Set(base.map(x=>`${x.player.id}:${x.type}`));osVisiblePlayers().forEach(p=>{const remaining=Math.max(0,(p.sessionsPurchased||0)-(p.sessionsUsed||0));if(remaining<=3&&!seen.has(`${p.id}:balance`))base.push({player:p,type:"balance",level:"high",icon:"◫",title:pt2Fa(`${p.name} has ${remaining} sessions remaining`,`${remaining} جلسه از اعتبار ${p.name} باقی مانده`),text:pt2Fa("Renew the package before the next training block.","پیش از بلوک تمرینی بعدی برای تمدید پکیج اقدام کنید.")});});return base.sort((a,b)=>(a.level==="high"?0:1)-(b.level==="high"?0:1));};
osActions=function(){return osAlerts().slice(0,4).map(a=>({player:a.player,label:a.type==="promotion"?osT("review_promotion"):a.type==="attendance"?osT("contact_player"):a.type==="pti"||a.type==="pdi"?osT("modify_plan"):a.type==="balance"?pt2Fa("Renew session package","تمدید اعتبار جلسات"):osT("schedule_assessment")}));};

function ptpLinkedProfile(u){if(u.playerId){const active=osPlayer(u.playerId),archived=OS.data.archivedPlayers.find(p=>p.id===u.playerId);return active?.name||(archived?`${archived.name} · ${pt2Fa("Archived","بایگانی‌شده")}`:pt2Fa("Missing player profile","پروفایل بازیکن یافت نشد"));}if(u.coachId)return pt2Coach(u.coachId)?.name||pt2Fa("Missing coach profile","پروفایل مربی یافت نشد");return pt2Fa("Academy account","حساب آکادمی");}
function ptpRenderUsers(root){root.innerHTML=`${osPageHead("ACCESS CONTROL",pt2Fa("User management","مدیریت کاربران"),pt2Fa("Create, review and deactivate academy access","ساخت، بررسی و غیرفعال‌سازی دسترسی‌های آکادمی"),`<button class="pt2-head-action" data-os-action="ptp-add-account">＋ ${pt2Fa("New account","حساب جدید")}</button>`)}<div class="os-card ptp-users" id="ptpUsers"><div class="ptp-loading">${pt2Fa("Loading secure accounts…","در حال دریافت حساب‌های امن…")}</div></div>`;fetch("/api/users",{cache:"no-store"}).then(r=>r.json()).then(out=>{PTP.users=out.users||[];const box=document.getElementById("ptpUsers");if(!box)return;box.innerHTML=`<div class="pt2-table-head"><span>${pt2Fa("User","کاربر")}</span><span>${pt2Fa("Role","نقش")}</span><span>${pt2Fa("Linked profile","پروفایل متصل")}</span><span>${pt2Fa("Access","دسترسی")}</span></div>${PTP.users.map(u=>`<div class="pt2-table-row"><span><strong>${osEsc(u.name)}</strong><small>@${osEsc(u.username)}</small></span><span>${osRoleLabel(u.role)}</span><span>${osEsc(ptpLinkedProfile(u))}</span><span>${u.username===OS.user.username?`<span class="os-status active">${pt2Fa("Current","فعلی")}</span>`:`<button class="ptp-access-toggle ${u.active?"active":""}" data-os-action="ptp-toggle-user" data-username="${u.username}">${u.active?pt2Fa("Active","فعال"):pt2Fa("Disabled","غیرفعال")}</button>`}</span></div>`).join("")}`;ptpLocalizeDataValues();}).catch(()=>{document.getElementById("ptpUsers").innerHTML=`<p class="pt2-empty">${pt2Fa("Could not load accounts.","دریافت حساب‌ها انجام نشد.")}</p>`;});}

pt2RenderAcademy=function(root){const a=OS.data.academy,programFa={"Private Coaching":"مربیگری خصوصی","Performance Analysis":"آنالیز عملکرد","Competition Preparation":"آمادگی مسابقه",Starter:"شروع",Foundation:"پایه",Development:"توسعه",Competition:"مسابقه",Elite:"نخبه"};root.innerHTML=`${osPageHead("PROTRACK ACADEMY PASSPORT",pt2Fa("Academy information","اطلاعات آکادمی"),pt2Fa("Brand, contact, programs and verified methodology","برند، راه‌های ارتباطی، برنامه‌ها و متدولوژی تأییدشده"))}<section class="ptp-academy-hero os-card"><div class="ptp-academy-logo"><img src="${a.logoDataUrl||"assets/protrack-official.png"}" alt="ProTrack"></div><div><span class="eyebrow">OFFICIAL ACADEMY PROFILE</span><h1>${osEsc(a.name)}</h1><p>${osEsc(OS.lang==="fa"?a.aboutFa:a.aboutEn)}</p><div class="pt2-pills"><span>${osEsc(a.location)}</span><span>${osEsc(a.founded)}</span></div></div></section><div class="pt2-two"><section class="os-card os-detail-card"><div class="os-section-head"><div><h2>${pt2Fa("Contact ProTrack","ارتباط با ProTrack")}</h2></div></div><div class="os-detail-grid">${[[pt2Fa("Phone","تلفن"),a.phone],["WhatsApp",a.whatsapp],["Instagram",a.instagram],[pt2Fa("Address","نشانی"),a.address]].map(([k,v])=>`<div class="os-detail"><small>${k}</small><strong>${osEsc(v||"—")}</strong></div>`).join("")}</div></section><section class="os-card os-detail-card"><div class="os-section-head"><div><h2>${pt2Fa("Programs & tracks","برنامه‌ها و مسیرها")}</h2></div></div><div class="ptp-tag-cloud">${[...a.programs,...a.tracks].map(x=>`<span>${osEsc(OS.lang==="fa"?(programFa[x]||x):x)}</span>`).join("")}</div></section></div><section class="os-card os-detail-card"><div class="os-section-head"><div><h2>${pt2Fa("Verified certifications","گواهی‌های تأییدشده")}</h2></div></div><div class="pt2-awards">${a.certifications.map(x=>`<article><span>✓</span><div><strong>${osEsc(x)}</strong><small>${pt2Fa("Active and verified","فعال و تأییدشده")}</small></div></article>`).join("")}</div></section>`;};

pt2RenderCoaches=function(root){root.innerHTML=`${osPageHead("COACH PASSPORTS",pt2Fa("Coaching team","تیم مربیگری"),pt2Fa("Identity, credentials and verification status","هویت حرفه‌ای، مدارک و وضعیت اعتبارسنجی"),`<button class="pt2-head-action" data-os-action="v2-add-coach">＋ ${pt2Fa("Register coach","ثبت مربی")}</button>`)}<div class="pt2-card-grid">${OS.data.coaches.map(c=>`<article class="os-card ptp-coach-passport"><header><span class="os-avatar">${osInitials(c.name)}</span><div><h2>${osEsc(c.name)}</h2><p>${osEsc(c.title)} · ${osEsc(c.specialty)}</p></div><span class="os-status ${c.active?"active":"inactive"}">${c.active?pt2Fa("Active","فعال"):pt2Fa("Inactive","غیرفعال")}</span></header><p>${osEsc(OS.lang==="fa"?c.bioFa:c.bioEn)}</p><div class="ptp-coach-meta"><span>${osEsc(c.email)}</span><span>${osEsc(c.phone)}</span></div><div class="ptp-cert-list">${c.certifications.map(x=>`<div><span>✓</span><div><strong>${osEsc(x.name)}</strong><small>${osEsc(x.issuer)} · ${pt2Fa("Expires","انقضا")} ${osEsc(x.expiry)}</small></div><b class="${x.verified?"verified":""}">${x.verified?pt2Fa("Verified","تأییدشده"):pt2Fa("Pending","در انتظار")}</b></div>`).join("")}</div></article>`).join("")}</div>`;};

pt2RenderLeaderboards=function(root){const players=osVisiblePlayers(),gain=p=>(p.ptiHistory?.length>1?p.ptiHistory.at(-1)-p.ptiHistory[0]:0),attendance=p=>p.attendance.attended/(p.attendance.attended+p.attendance.missed||1),readiness={Ready:0,Monitor:1,"Not Ready":2,"Insufficient Data":3};const boards=[[pt2Fa("Monthly performance","عملکرد ماه"),[...players].sort((a,b)=>b.pti-a.pti),p=>`PTI ${osScore(p.pti)}`],[pt2Fa("Most improved","بیشترین پیشرفت"),[...players].sort((a,b)=>gain(b)-gain(a)),p=>`${gain(p)>=0?"+":""}${gain(p).toFixed(1)} PTI`],[pt2Fa("Attendance champion","قهرمان حضور"),[...players].sort((a,b)=>attendance(b)-attendance(a)),p=>`${Math.round(attendance(p)*100)}%`],[pt2Fa("Promotion candidates","نامزدهای ارتقا"),[...players].sort((a,b)=>(readiness[osPromotion(a).status]??4)-(readiness[osPromotion(b).status]??4)),p=>osT(osPromotion(p).status==="Ready"?"ready":"monitor")]];root.innerHTML=`${osPageHead("MOTIVATION SYSTEM",pt2Fa("Monthly academy leaders","برترین‌های ماه آکادمی"),pt2Fa("Celebrate progress, consistency and readiness","تقدیر از پیشرفت، استمرار و آمادگی"))}<div class="ptp-leader-grid">${boards.map(([title,list,value])=>`<section class="os-card pt2-leader"><h2>${title}</h2>${list.slice(0,5).map((p,i)=>`<div><b>${i+1}</b><span class="os-avatar">${osInitials(p.name)}</span><span><strong>${osEsc(p.name)}</strong><small>${osEsc(p.primaryFocus)}</small></span><em>${value(p)}</em></div>`).join("")}</section>`).join("")}</div><section class="os-card ptp-badge-wall"><div class="os-section-head"><div><h2>${pt2Fa("Achievement badges","نشان‌های افتخار")}</h2><p>${pt2Fa("Milestones earned across the academy","دستاوردهای ثبت‌شده در آکادمی")}</p></div></div>${OS.data.achievements.map(x=>`<article><span>✦</span><strong>${osEsc(x.title)}</strong><small>${osEsc(pt2PlayerName(x.playerId))}</small></article>`).join("")}</section>`;};

osOpenAddPlayer=function(){ptpOpenPlayerRegistration();};
function ptpOpenPlayerRegistration(){const fa=OS.lang==="fa",coaches=OS.data.coaches.filter(c=>c.active);const fields=`<div class="pt2-field-pair">${ptpField(fa?"نام کامل":"Full name","name")}${ptpField(fa?"شماره تماس":"Phone","phone")}</div><div class="pt2-field-pair">${ptpField(fa?"ملیت":"Nationality","nationality","","text",false)}${ptpField(fa?"سن":"Age","age","","number",false)}</div><div class="os-field"><label>${fa?"مربی مسئول":"Assigned coach"}</label><select name="coachId">${coaches.map(c=>`<option value="${c.id}">${osEsc(c.name)}</option>`).join("")}</select></div><div class="os-field"><label>${fa?"پیشینه ورزشی":"Sports background"}</label><textarea name="sportsBackground"></textarea></div><div class="os-field"><label>${fa?"هدف‌های رشد":"Development goals"}</label><textarea name="goals"></textarea></div><div class="pt2-field-pair">${ptpField(fa?"نام کاربری":"Username","username")}${ptpField(fa?"رمز عبور (۱۰+ کاراکتر)":"Password (10+ characters)","password","","password")}</div>`;osOpenModal(osModalFrame(fa?"ثبت بازیکن":"Player registration",fa?"پروفایل کامل و حساب امن بازیکن را هم‌زمان بسازید.":"Create the complete profile and secure player account together.",`<form class="os-form" id="ptpPlayerRegistration">${fields}<p class="pt2-form-error" id="ptpPlayerError"></p><button class="os-primary-button">${fa?"ساخت بازیکن و حساب":"Create player & account"}</button></form>`));document.getElementById("ptpPlayerRegistration").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target),id=pt2Id("p"),coach=pt2Coach(fd.get("coachId")),payload={role:"player",name:fd.get("name"),username:fd.get("username"),password:fd.get("password"),playerId:id};const res=await fetch("/api/users/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),out=await res.json();if(!res.ok){document.getElementById("ptpPlayerError").textContent=out.message||"Account creation failed";return;}const p={id,name:fd.get("name"),gender:"—",age:Number(fd.get("age"))||"",phone:fd.get("phone"),emergency:"—",startDate:osDateOffset(0),stage:"Starter",track:"Starter",status:"Active",pdi:null,pti:null,rubricMin:null,confidence:"LOW",sessionsCompleted:0,attendance:{attended:0,missed:0,consecutive:0},coachId:fd.get("coachId"),coach:coach?.name||"—",coachNotes:"",membership:"Starter",sessionsPurchased:0,sessionsUsed:0,primaryFocus:"Assessment required",pdiHistory:[],ptiHistory:[],commitment:null,commitmentTrend:"stable",nationality:fd.get("nationality")||"—",dominantHand:"Right",playingSide:"Right",sportsBackground:fd.get("sportsBackground"),goals:fd.get("goals"),rankings:{club:null,city:null,national:null,international:null}};OS.data.players.push(p);OS.data.journey.push({id:pt2Id("j"),playerId:id,date:osDateOffset(0),title:"Joined ProTrack",detail:"Player registration completed",type:"milestone"});pt2Save();osCloseModal();OS.profileId=id;OS.profileTab="passport";osRender("player");});}

function ptpOpenCoachRegistration(){const fa=OS.lang==="fa";const fields=`${ptpField(fa?"نام کامل":"Full name","name")}${ptpField(fa?"سمت":"Title","title",fa?"مربی دستیار":"Assistant Coach")}${ptpField(fa?"تخصص":"Specialty","specialty")}${ptpField(fa?"ایمیل":"Email","email","","email",false)}<div class="pt2-field-pair">${ptpField(fa?"نام مدرک":"Certification","certification")}${ptpField(fa?"صادرکننده":"Issuer","issuer")}</div><div class="pt2-field-pair">${ptpField(fa?"تاریخ انقضا":"Expiry","expiry","","date")}${ptpField(fa?"تلفن":"Phone","phone","","text",false)}</div><div class="pt2-field-pair">${ptpField(fa?"نام کاربری":"Username","username")}${ptpField(fa?"رمز عبور (۱۰+ کاراکتر)":"Password (10+ characters)","password","","password")}</div>`;osOpenModal(osModalFrame(fa?"ثبت مربی":"Coach registration",fa?"پاسپورت حرفه‌ای و حساب امن مربی را بسازید.":"Create the coach passport and secure account.",`<form class="os-form" id="ptpCoachRegistration">${fields}<p class="pt2-form-error" id="ptpCoachError"></p><button class="os-primary-button">${fa?"ساخت مربی و حساب":"Create coach & account"}</button></form>`));document.getElementById("ptpCoachRegistration").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target),id=pt2Id("c"),payload={role:"assistant",coachId:id,name:fd.get("name"),username:fd.get("username"),password:fd.get("password")};const res=await fetch("/api/users/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),out=await res.json();if(!res.ok){document.getElementById("ptpCoachError").textContent=out.message||"Account creation failed";return;}OS.data.coaches.push({id,name:fd.get("name"),title:fd.get("title"),phone:fd.get("phone"),email:fd.get("email"),specialty:fd.get("specialty"),bio:"",certifications:[{name:fd.get("certification"),issuer:fd.get("issuer"),expiry:fd.get("expiry"),verified:true}],active:true});pt2Save();osCloseModal();osRender("coaches");});}

function ptpOpenAccountRegistration(){const fa=OS.lang==="fa",profiles=`<option value="head">${fa?"آکادمی · سرمربی جدید":"Academy · New Head Coach"}</option><optgroup label="${fa?"مربیان":"Coaches"}">${OS.data.coaches.map(c=>`<option value="assistant:${c.id}">${osEsc(c.name)} · ${fa?"مربی":"Coach"}</option>`).join("")}</optgroup><optgroup label="${fa?"بازیکنان":"Players"}">${OS.data.players.filter(p=>!p.archived).map(p=>`<option value="player:${p.id}">${osEsc(p.name)} · ${fa?"بازیکن":"Player"}</option>`).join("")}</optgroup>`;const fields=`${ptpField(fa?"نام کامل":"Full name","name")}<div class="os-field"><label>${fa?"پروفایل و نقش":"Profile & role"}</label><select name="link">${profiles}</select></div>${ptpField(fa?"نام کاربری":"Username","username")}${ptpField(fa?"رمز عبور (۱۰+ کاراکتر)":"Password (10+ characters)","password","","password")}`;osOpenModal(osModalFrame(fa?"حساب جدید":"New account",fa?"برای یک پروفایل موجود دسترسی امن و متصل بسازید.":"Create secure, linked access for an existing profile.",`<form class="os-form" id="ptpAccountForm">${fields}<p class="pt2-form-error" id="ptpAccountError"></p><button class="os-primary-button">${fa?"ساخت حساب":"Create account"}</button></form>`));document.getElementById("ptpAccountForm").addEventListener("submit",async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.target).entries()),[role,id]=raw.link.split(":"),data={name:raw.name,username:raw.username,password:raw.password,role,coachId:role==="assistant"?id:null,playerId:role==="player"?id:null},res=await fetch("/api/users/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),out=await res.json();if(!res.ok){document.getElementById("ptpAccountError").textContent=out.message||"Account creation failed";return;}osCloseModal();osRender("users");});}

function ptpOpenTournament(playerId){const fa=OS.lang==="fa",fields=`${ptpField(fa?"نام مسابقه":"Tournament name","name")}${ptpField(fa?"تاریخ":"Date","date",osDateOffset(0),"date")}<div class="pt2-field-pair">${ptpField(fa?"سطح":"Level","level")}${ptpField(fa?"نتیجه":"Result","result")}</div><div class="pt2-field-pair">${ptpField(fa?"هم‌بازی":"Partner","partner")}${ptpField(fa?"جایگاه":"Position","position")}</div>${ptpField(fa?"محل":"Location","location","","text",false)}`;osOpenModal(osModalFrame(fa?"ثبت نتیجه مسابقه":"Tournament result",fa?"سابقه رسمی مسابقه را به پاسپورت بازیکن اضافه کنید.":"Add the official result to the player passport.",`<form class="os-form" id="ptpTournamentForm">${fields}<button class="os-primary-button">${fa?"ثبت نتیجه":"Save result"}</button></form>`));document.getElementById("ptpTournamentForm").addEventListener("submit",e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target).entries());OS.data.tournaments.push({id:pt2Id("t"),...o,status:"Completed",playerIds:[playerId]});pt2Save();osCloseModal();OS.profileTab="competition";osRender("player");});}

function ptpLocalizeDataValues(){if(OS.lang!=="fa")return;const map={"Assistant Coach":"مربی دستیار","Head Coach":"سرمربی","Performance & academy direction":"مدیریت عملکرد و آکادمی","Foundation & tactical development":"توسعه پایه و تاکتیک","Competition preparation":"آمادگی مسابقه","Competition Readiness":"آمادگی مسابقه","Decision making":"تصمیم‌گیری","Movement structure":"ساختار حرکت","Performance review":"بازبینی عملکرد","Match review":"بازبینی مسابقه","Promotion block":"بلوک ارتقا","Wall play":"بازی با دیوار","Groundstroke":"ضربه زمینی","Positioning":"جای‌گیری","Volley":"والی","Development":"توسعه","Foundation":"پایه","Competition":"مسابقه","Starter":"شروع","Elite":"نخبه","Training":"تمرین","Assessment":"ارزیابی","Video Analysis":"آنالیز ویدیو","Match Analysis":"آنالیز مسابقه","Male":"مرد","Female":"زن","Registered":"ثبت‌نام‌شده","Completed":"تکمیل‌شده","Club":"باشگاهی","City":"شهری","National":"کشوری","International":"بین‌المللی"};const roots=[document.getElementById("view"),document.querySelector(".sidebar")].filter(Boolean);roots.forEach(root=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{let value=n.nodeValue;Object.entries(map).sort((a,b)=>b[0].length-a[0].length).forEach(([en,fa])=>value=value.replaceAll(en,fa));n.nodeValue=value;});});}

function ptpEnhanceShell(){
  const aside=document.querySelector(".sidebar");if(!aside||!OS.user.loggedIn)return;aside.hidden=false;const items=OS.user.role==="head"?[["home","⌂",pt2Fa("Command center","مرکز فرمان")],["players","◎",pt2Fa("Players","بازیکنان")],["analysis","◇",pt2Fa("AI Analyst","آنالیز هوشمند")],["registrations","↳",pt2Fa("Registrations","ثبت‌نام‌ها")],["coaches","♙",pt2Fa("Coaches","مربیان")],["users","◉",pt2Fa("User access","دسترسی کاربران")],["leaderboards","✦",pt2Fa("Motivation","انگیزش")],["settings","⚙",pt2Fa("Settings","تنظیمات")]]:[["home","⌂",pt2Fa("Overview","نمای کلی")],["players","◎",pt2Fa("Players","بازیکنان")],["analysis","◇",pt2Fa("Reports","گزارش‌ها")],["programs","▤",pt2Fa("Programs","برنامه‌ها")],["settings","⚙",pt2Fa("Settings","تنظیمات")]];aside.innerHTML=`<div class="ptp-side-brand"><img src="assets/icon-192.png" alt=""><span><strong>PROTRACK</strong><small>ACADEMY OS</small></span></div><nav>${items.map(([view,icon,label])=>`<button class="${OS.current===view?"active":""}" data-os-view="${view}"><i>${icon}</i><span>${label}</span></button>`).join("")}</nav><div class="ptp-side-user"><span class="os-avatar">${osInitials(OS.user.name)}</span><div><strong>${osEsc(OS.user.name)}</strong><small>${osRoleLabel()}</small></div></div>`;
  if(innerWidth<700&&pt2CanCoach())document.querySelectorAll(".os-player-row").forEach(row=>{if(row.querySelector(".ptp-swipe-actions"))return;row.insertAdjacentHTML("beforeend",`<div class="ptp-swipe-actions"><button data-os-action="quick-note" data-id="${row.dataset.id||""}">✎</button></div>`);let sx=0;row.addEventListener("touchstart",e=>sx=e.touches[0].clientX,{passive:true});row.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)row.classList.toggle("swiped",dx<0);},{passive:true});});
  ptpLocalizeDataValues();
}

osRender=function(view=OS.current){if(view==="users"){if(!PT2.authReady||!OS.user.loggedIn){osOpenLogin();return;}if(!pt2CanManage()){toast(pt2Fa("Head Coach access required.","این بخش فقط برای سرمربی است."));view="home";}else{OS.current=view;osSetNav(view);const root=document.getElementById("view");ptpRenderUsers(root);document.documentElement.lang=OS.lang==="fa"?"fa":"en";document.documentElement.dir=OS.lang==="fa"?"rtl":"ltr";ptpEnhanceShell();return;}}PTP_PREV_RENDER(view);ptpEnhanceShell();};

document.addEventListener("click",async event=>{const el=event.target.closest("[data-os-action]");if(!el)return;const a=el.dataset.osAction,handled=["ptp-start-setup","ptp-setup-back","ptp-add-account","ptp-toggle-user","ptp-add-tournament","v2-add-coach"];if(!handled.includes(a))return;event.preventDefault();event.stopImmediatePropagation();if(a==="ptp-start-setup"){if(PTP.setupRequired)ptpOpenSetup(1);else osOpenModal(osModalFrame(pt2Fa("Registration & access","ثبت‌نام و دسترسی"),pt2Fa("This academy is already configured. Sign in as Head Coach to create coach, assistant and player accounts.","این آکادمی راه‌اندازی شده است. برای ساخت حساب سرمربی، مربی دستیار یا بازیکن با حساب سرمربی وارد شوید."),`<button class="os-primary-button" data-os-action="close-modal">${pt2Fa("Back to sign in","بازگشت به ورود")}</button>`));}if(a==="ptp-setup-back")ptpOpenSetup(Number(el.dataset.step)-1);if(a==="ptp-add-account")ptpOpenAccountRegistration();if(a==="ptp-add-tournament")ptpOpenTournament(el.dataset.player);if(a==="v2-add-coach")ptpOpenCoachRegistration();if(a==="ptp-toggle-user"){const res=await fetch("/api/users/toggle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:el.dataset.username})});if(res.ok)osRender("users");}},true);

(async()=>{try{const status=await fetch("/api/setup/status",{cache:"no-store"}).then(r=>r.json());PTP.setupRequired=!!status.setupRequired;if(PTP.setupRequired){PT2.authReady=true;OS.user.loggedIn=false;osSave();ptpOpenSetup(1);}else if(new URLSearchParams(location.search).get("setup")==="preview")ptpOpenSetup(1);}catch(_){}})();
